name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  # If you later move code to repo root, change this to "."
  APP_DIR: "Grond-main 2"

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          ls -la "${{ env.APP_DIR }}" || true
          ls -la "${{ env.APP_DIR }}/scripts" || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (from subdir)
        run: |
          python -m pip install --upgrade pip
          if [ -f "${{ env.APP_DIR }}/requirements.txt" ]; then
            pip install --no-cache-dir -r "${{ env.APP_DIR }}/requirements.txt"
          elif [ -f "requirements.txt" ]; then
            pip install --no-cache-dir -r "requirements.txt"
          fi
          # safety net in case requirements.txt missed anything used at import time
          pip install --no-cache-dir requests ruff pytest joblib boto3 scikit-learn
          python - <<'PY'
import importlib, sys
try:
    importlib.import_module("requests")
    print("requests OK")
except Exception as e:
    sys.exit(f"requests missing: {e}")
PY

      - name: Lint (ruff, warn-only)
        run: ruff check . || true

      - name: Validate repository (syntax + internal import symbols)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
        run: |
          python -u "${{ env.APP_DIR }}/scripts/repo_validation.py"

      - name: Contract checks (dataset + classifier wiring)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
          MODEL_URI: local://dummy
        run: |
          python -u "${{ env.APP_DIR }}/scripts/contract_checks.py"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/potential-broccoli:ci

      - name: Run validations inside Docker image
        env:
          APP_DIR: ${{ env.APP_DIR }}
          MODEL_URI: local://dummy
        run: |
          docker run --rm \
            -e MODEL_URI \
            -e PYTHONPATH="/app/${APP_DIR}" \
            local/potential-broccoli:ci \
            bash -lc 'python -u "${APP_DIR}/scripts/repo_validation.py" && python -u "${APP_DIR}/scripts/contract_checks.py"'
