name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  APP_DIR: "Grond-main 2"   # <-- your subfolder with a space

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          ls -la "${{ env.APP_DIR }}/scripts" || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest ruff joblib boto3 scikit-learn

      - name: Validate repository (syntax + internal import symbols)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
        run: |
          python -u "${{ env.APP_DIR }}/scripts/repo_validation.py"

      - name: Contract checks (dataset + classifier wiring)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
          MODEL_URI: local://dummy
        run: |
          python -u "${{ env.APP_DIR }}/scripts/contract_checks.py"

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/potential-broccoli:ci

      - name: Run validations inside Docker image
        env:
          APP_DIR: ${{ env.APP_DIR }}
          MODEL_URI: local://dummy
        run: |
          docker run --rm \
            -e MODEL_URI \
            -e PYTHONPATH="/app/${APP_DIR}" \
            local/potential-broccoli:ci \
            bash -lc 'python -u "${APP_DIR}/scripts/repo_validation.py" && python -u "${APP_DIR}/scripts/contract_checks.py"'
