name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  # Change to "." if you later move code to repo root
  APP_DIR: "Grond-main 2"

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          ls -la "${{ env.APP_DIR }}" || true
          ls -la "${{ env.APP_DIR }}/scripts" || true
          ls -la "${{ env.APP_DIR }}/Dockerfile" || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (from subdir)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [[ -f "${{ env.APP_DIR }}/requirements.txt" ]]; then
            pip install --no-cache-dir -r "${{ env.APP_DIR }}/requirements.txt"
          elif [[ -f "requirements.txt" ]]; then
            pip install --no-cache-dir -r "requirements.txt"
          fi
          # Safety net for import-time deps used by validators
          pip install --no-cache-dir requests ruff pytest joblib boto3 scikit-learn

      - name: Lint (ruff, warn-only)
        run: ruff check . || true

      - name: Validate repository (syntax + internal import symbols)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
        run: |
          python -u "${{ env.APP_DIR }}/scripts/repo_validation.py"

      - name: Contract checks (dataset + classifier wiring)
        env:
          PYTHONPATH: "${{ github.workspace }}/${{ env.APP_DIR }}"
          MODEL_URI: local://dummy
        run: |
          python -u "${{ env.APP_DIR }}/scripts/contract_checks.py"

      # --- Docker with Buildx (docker driver) ---
      - name: Set up Docker Buildx (docker driver)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build image (load into daemon)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_DIR }}              # subfolder context
          file: ${{ env.APP_DIR }}/Dockerfile      # Dockerfile in that subfolder
          push: false
          load: true                               # required for docker run later
          tags: local/potential-broccoli:ci
          provenance: false
          sbom: false

      - name: Run validations inside image
        env:
          MODEL_URI: local://dummy
        run: |
          docker run --rm \
            -e MODEL_URI \
            -e PYTHONPATH="/app" \
            local/potential-broccoli:ci \
            bash -lc 'python -u scripts/repo_validation.py && python -u scripts/contract_checks.py'
