name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install --no-cache-dir -r requirements.txt
          fi
          pip install --no-cache-dir pytest ruff joblib boto3 scikit-learn

      - name: Lint (ruff, warn-only)
        run: |
          ruff check . || true

      - name: Validate repository (syntax + internal import symbols)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -u scripts/repo_validation.py

      - name: Contract checks (dataset + classifier wiring)
        env:
          PYTHONPATH: ${{ github.workspace }}
          MODEL_URI: local://dummy
        run: |
          python -u scripts/contract_checks.py

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/potential-broccoli:ci

      - name: Run validations inside Docker image
        env:
          MODEL_URI: local://dummy
        run: |
          docker run --rm \
            -e MODEL_URI \
            -e PYTHONPATH=/app \
            local/potential-broccoli:ci \
            bash -lc "python -u scripts/repo_validation.py && python -u scripts/contract_checks.py"
