name: Presign Existing Model (no-train)

on:
  workflow_dispatch:
    inputs:
      object_key:
        description: "Full S3 object key (e.g., models/xgb_classifier.pipeline.joblib)"
        required: true
        default: "models/xgb_classifier.pipeline.joblib"
      expires_in:
        description: "TTL seconds (must be <= role session; default 21600 = 6h)"
        required: false
        default: "21600"

env:
  AWS_REGION: eu-north-1
  BUCKET: tinabobina

permissions:
  id-token: write
  contents: read

jobs:
  presign:
    runs-on: ubuntu-latest
    outputs:
      s3_uri: ${{ steps.presign.outputs.s3_uri }}
      presigned_url: ${{ steps.presign.outputs.presigned_url }}

    steps:
      - name: Checkout (for OIDC context only)
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719070647059:role/tigermoon
          role-session-name: tinabobina-presign
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 21600  # 6h session; URL must not exceed this

      - name: Presign specified object (GET) and verify with Range GET
        id: presign
        env:
          IN_KEY: ${{ inputs.object_key }}
          EXPIRES_IN: ${{ inputs.expires_in }}
          BUCKET: ${{ env.BUCKET }}
        run: |
          set -euo pipefail

          [[ -n "${IN_KEY}" ]] || { echo "Input 'object_key' is required." >&2; exit 1; }

          # Ensure the object exists
          aws s3api head-object --bucket "${BUCKET}" --key "${IN_KEY}" >/dev/null

          # Clamp TTL to session (6h) and S3 max (7d)
          EXPIRES="${EXPIRES_IN:-21600}"
          if [[ "${EXPIRES}" -gt 21600 ]]; then
            echo "expires_in ${EXPIRES} > session 21600; clamping to 21600." >&2
            EXPIRES=21600
          fi
          if [[ "${EXPIRES}" -gt 604800 ]]; then EXPIRES=604800; fi

          URI="s3://${BUCKET}/${IN_KEY}"
          URL="$(aws s3 presign "${URI}" --expires-in "${EXPIRES}")"

          # ✅ Validate using GET with Range (method must match signature)
          code=$(curl -sS -H "Range: bytes=0-0" -o /dev/null -w "%{http_code}" --max-time 30 "${URL}" || echo "ERR")

          if [[ "${code}" != "200" && "${code}" != "206" ]]; then
            echo "Presigned URL GET returned ${code}. Response preview:" >&2
            curl -sS --max-time 30 "${URL}" | head -c 400 >&2 || true
            exit 1
          fi

          echo "s3_uri=${URI}"        >> "$GITHUB_OUTPUT"
          echo "presigned_url=${URL}" >> "$GITHUB_OUTPUT"

          echo "S3 URI: ${URI}"
          echo "Presigned URL (paste into QuantConnect):"
          echo "${URL}"

      - name: Write URL files and job summary
        if: ${{ always() }}
        run: |
          echo "${{ steps.presign.outputs.s3_uri }}" > s3_uri.txt || true
          echo "${{ steps.presign.outputs.presigned_url }}" > presigned_url.txt || true

          {
            echo "### Model download links"
            echo
            echo "- **S3 URI**"
            echo
            echo "  \`${{ steps.presign.outputs.s3_uri }}\`"
            echo
            echo "#### Presigned URL (paste into QuantConnect)"
            echo
            echo '```'
            echo "${{ steps.presign.outputs.presigned_url }}"
            echo '```'
            echo
            echo "_Note: Valid up to the role session (6h here). Regenerate as needed._"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload URL artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: presigned-model-url
          path: |
            s3_uri.txt
            presigned_url.txt
