name: Presign Existing Model (no-train)

on:
  workflow_dispatch:
    inputs:
      object_key:
        description: "Full S3 object key to presign (e.g., models/xgb_classifier.pipeline.joblib)"
        required: true
        default: "models/xgb_classifier.pipeline.joblib"
      expires_in:
        description: "TTL seconds (max 604800 = 7 days)"
        required: false
        default: "604800"

env:
  AWS_REGION: eu-north-1
  BUCKET: tinabobina

permissions:
  id-token: write
  contents: read

jobs:
  presign:
    runs-on: ubuntu-latest
    outputs:
      s3_uri: ${{ steps.presign.outputs.s3_uri }}
      presigned_url: ${{ steps.presign.outputs.presigned_url }}

    steps:
      - name: Checkout (for OIDC context only)
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719070647059:role/tigermoon
          role-session-name: tinabobina-presign
          aws-region: ${{ env.AWS_REGION }}

      - name: Presign specified object
        id: presign
        env:
          IN_KEY: ${{ inputs.object_key }}
          EXPIRES: ${{ inputs.expires_in }}
          BUCKET: ${{ env.BUCKET }}
        run: |
          set -euo pipefail

          if [[ -z "${IN_KEY}" ]]; then
            echo "Input 'object_key' is required." >&2
            exit 1
          fi

          # sanity check object exists
          aws s3api head-object --bucket "${BUCKET}" --key "${IN_KEY}" >/dev/null

          # clamp TTL to 7 days
          if [[ "${EXPIRES}" -gt 604800 ]]; then EXPIRES=604800; fi

          URI="s3://${BUCKET}/${IN_KEY}"
          URL="$(aws s3 presign "${URI}" --expires-in "${EXPIRES}")"

          echo "s3_uri=${URI}"        >> "$GITHUB_OUTPUT"
          echo "presigned_url=${URL}" >> "$GITHUB_OUTPUT"

          echo "S3 URI: ${URI}"
          echo "Presigned URL (paste into QuantConnect):"
          echo "${URL}"

      - name: Write URL files and job summary
        if: ${{ always() }}
        run: |
          echo "${{ steps.presign.outputs.s3_uri }}" > s3_uri.txt || true
          echo "${{ steps.presign.outputs.presigned_url }}" > presigned_url.txt || true

          {
            echo "### Model download links"
            echo ""
            echo "- **S3 URI**"
            echo ""
            echo "  \`${{ steps.presign.outputs.s3_uri }}\`"
            echo ""
            echo "#### Presigned URL (paste into QuantConnect)"
            echo ""
            echo '```'
            echo "${{ steps.presign.outputs.presigned_url }}"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload URL artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: presigned-model-url
          path: |
            s3_uri.txt
            presigned_url.txt
