name: Presign Existing Model (12h, no-train)

on:
  workflow_dispatch:
    inputs:
      object_key:
        description: "Full S3 object key (e.g., models/xgb_classifier.pipeline.joblib)"
        required: true
        default: "models/xgb_classifier.pipeline.joblib"

env:
  AWS_REGION: eu-north-1
  BUCKET: tinabobina

permissions:
  id-token: write
  contents: read

jobs:
  presign:
    runs-on: ubuntu-latest
    outputs:
      s3_uri: ${{ steps.presign.outputs.s3_uri }}
      presigned_url: ${{ steps.presign.outputs.presigned_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC, 12h session)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719070647059:role/tigermoon
          role-session-name: tinabobina-presign
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 43200  # 12h (ensure the role's Max session duration is set to 12h)

      - name: Presign S3 object for 12h and validate
        id: presign
        env:
          IN_KEY: ${{ inputs.object_key }}
          BUCKET: ${{ env.BUCKET }}
        run: |
          set -euo pipefail

          # Ensure object exists
          aws s3api head-object --bucket "${BUCKET}" --key "${IN_KEY}" >/dev/null

          # With OIDC the presigned URL cannot outlive the STS session.
          EXPIRES=43200  # exact 12h

          URI="s3://${BUCKET}/${IN_KEY}"
          URL="$(aws s3 presign "${URI}" --expires-in "${EXPIRES}")"

          # Validate URL by doing a range GET (HEAD can fail on presigned URLs)
          code=$(curl -sS -H "Range: bytes=0-0" -o /dev/null -w "%{http_code}" --max-time 30 "${URL}" || echo "ERR")
          if [[ "${code}" != "200" && "${code}" != "206" ]]; then
            echo "Presigned URL validation failed with HTTP ${code}" >&2
            curl -sS --max-time 30 "${URL}" | head -c 400 >&2 || true
            exit 1
          fi

          echo "s3_uri=${URI}"        >> "$GITHUB_OUTPUT"
          echo "presigned_url=${URL}" >> "$GITHUB_OUTPUT"

          echo "S3 URI: ${URI}"
          echo "Presigned URL (paste into Render env MODEL_PRESIGNED_URL):"
          echo "${URL}"

      - name: Write artifacts and summary
        if: ${{ always() }}
        run: |
          echo "${{ steps.presign.outputs.s3_uri }}" > s3_uri.txt || true
          echo "${{ steps.presign.outputs.presigned_url }}" > presigned_url.txt || true

          {
            echo "### 12-hour Presigned Model URL"
            echo
            echo "- **S3 URI**"
            echo
            echo "  \`${{ steps.presign.outputs.s3_uri }}\`"
            echo
            echo "- **Presigned URL** (paste into Render → Environment → \`MODEL_PRESIGNED_URL\`)"
            echo
            echo '```'
            echo "${{ steps.presign.outputs.presigned_url }}"
            echo '```'
            echo
            echo "_Note:_ URL lifetime is 12 hours (OIDC session cap). Regenerate before expiry or automate rotation."
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload presigned URL artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: presigned-model-url
          path: |
            s3_uri.txt
            presigned_url.txt
