name: Train & Publish HCBC Model

on:
  workflow_dispatch:
    inputs:
      n_trials:
        description: 'Optuna trials'
        required: false
        default: '40'
      folds:
        description: 'Walk-forward folds'
        required: false
        default: '6'
      embargo_rows:
        description: 'Embargo rows between train/val'
        required: false
        default: '200'

permissions:
  contents: write
  id-token: write

env:
  PYTHONUNBUFFERED: "1"
  RAW_PREP_OUT: data/movement_training_data.csv
  HCBC_OUT: data/multiH_binary.csv
  MODEL_BUNDLE: Resources/xgb_hcbc.bundle.joblib

  # Provided by your repo env/vars
  AWS_REGION: ${{ vars.AWS_REGION }}
  ML_MODEL_PATH: ${{ vars.ML_MODEL_PATH }}

jobs:
  train-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r "Grond-main 2/requirements.txt"
          # pins for trainer/runtime
          pip install "xgboost>=1.7,<2.0" "scikit-learn>=1.3,<1.6" "optuna>=3.5" "fastapi" "pydantic" "uvicorn[standard]"

      # ======== 1) Existing prep (unchanged) ========
      - name: Prepare (existing pipeline)
        working-directory: "Grond-main 2"
        env:
          # keep if your prep pulls data via Polygon (else remove)
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p data Resources
          python prepare_training_data.py --out "${RAW_PREP_OUT}"

      - name: Verify prepared dataset
        run: |
          set -euo pipefail
          test -s "${RAW_PREP_OUT}"
          python - << 'PY'
          import pandas as pd, os
          p=os.environ["RAW_PREP_OUT"]; df=pd.read_csv(p)
          print("Prepared rows:", len(df)); print(df.columns.tolist()[:40])
          PY

      # ======== 2) Convert to HCBC schema ========
      - name: Convert to binary HCBC dataset
        working-directory: "Grond-main 2"
        run: |
          set -euo pipefail
          python prepare_hcbc_dataset.py \
            --in "${RAW_PREP_OUT}" \
            --out "${HCBC_OUT}" \
            --h 2 \
            --drop-neutral
          test -s "${HCBC_OUT}"

      - name: Show HCBC head
        run: |
          python - << 'PY'
          import pandas as pd, os
          p=os.environ["HCBC_OUT"]; df=pd.read_csv(p)
          print(df.head(5).to_string())
          print("Columns:", df.columns.tolist()[:60])
          PY

      # ======== 3) Train + Optuna + calibration ========
      - name: Train HCBC (XGBoost + Optuna)
        run: |
          set -euo pipefail
          mkdir -p "Grond-main 2/Resources"
          python "audit_fixes/train_hcbc_xgb_optuna.py" \
            --data "${HCBC_OUT}" \
            --out "${MODEL_BUNDLE}" \
            --n-trials "${{ github.event.inputs.n_trials || 40 }}" \
            --folds "${{ github.event.inputs.folds || 6 }}" \
            --embargo-rows "${{ github.event.inputs.embargo_rows || 200 }}" \
            --seed 42
          test -s "${MODEL_BUNDLE}"

      # ======== 4) Publish artifacts ========
      - name: Upload artifacts (bundle + reports)
        uses: actions/upload-artifact@v4
        with:
          name: hcbc_model_bundle
          path: |
            "${{ env.MODEL_BUNDLE }}"
            "Grond-main 2/Resources/hcbc_cv_report.json"
            "Grond-main 2/Resources/hcbc_thresholds.json"
            "Grond-main 2/Resources/hcbc_features.json"
          retention-days: 30

      # ======== 5) Configure AWS via OIDC (no secrets in if:) ========
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use the same role you already use for OIDC in this repo
          role-to-assume: arn:aws:iam::719070647059:role/tigermoon
          aws-region: ${{ env.AWS_REGION || 'us-east-1' }}

      - name: Upload model to S3 (ML_MODEL_PATH)
        if: ${{ env.ML_MODEL_PATH }}
        run: |
          set -euo pipefail
          echo "Uploading model to ${ML_MODEL_PATH}"
          aws s3 cp "${MODEL_BUNDLE}" "${ML_MODEL_PATH}" --only-show-errors
